[bugfix] Update atomic-openshift-installer command syntax
If you run atomic-openshift-installer as documented, you will receive the following error:
Usage: atomic-openshift-installer [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "--ansible-playbook-directory" / "-a": Directory "openshift-ansible/" does not exist.

Patch updates to use proper command syntax of:
atomic-openshift-installer -a openshift-ansible/ install